name: $(Date:yyyy.MM.dd)$(Rev:.r)

trigger: none

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/BuildTemplates

variables:
  - template: environments/znl-aks1.yaml@templates
  - template: variables/shared.yaml@templates
  - template: ../common-variables.yaml
  - template: znl-pr-variables.yaml
  
stages:
  - stage: UnitTestBuild
    displayName: Build and Quality
    variables:
      Build_Output_Folder: $(System.DefaultWorkingDirectory)/output/
    
    jobs:
    - job: Unit_Tests

      pool:
        name: "Hosted VS2017"

      steps:
        - template: steps/nuget-feed-auth.yaml@templates
          parameters:
            Nuget_Config: ${{ variables.Nuget_Config_Location }}

        - task: DotNetCoreCLI@2
          displayName: Build Shell App Solution With UnitTest
          inputs:
            projects: "${{ variables.Build_Projects }}"
            arguments: "--configuration ${{ variables.BuildConfiguration }} /p:Platform=Tests"

        - task: VSTest@2
          displayName: Run Unit Tests
          inputs:
            testAssemblyVer2: |
              **\*UnitTests*.dll
              !**\*TestAdapter.dll
              !**\obj\**
            publishTestResults: true
            codeCoverageEnabled: true
            runInParallel: true
            continueOnError: true # Allow sonarcloud to finish collecting data

  - stage: AndroidAppBuild
    displayName: Android App Build
    dependsOn: [UnitTestBuild]
    variables:
      Platform: ${{ variables.AndroidPlatform }}
      OutputDirectory: '$(build.binariesDirectory)/${{ variables.BuildConfiguration }}'
      AppBuildNumber: $[counter('${{ variables.AppVersionMajorMinor}}{{variables.BuildType}}', 0)]
      AppVersionNumber: ${{ variables.AppVersionMajorMinor}}$(AppBuildNumber)  
    jobs:
    - template: ../jobs/android-build-job-speedy.yaml
      parameters:
        Platform: $(Platform)
        OutputDirectory: $(OutputDirectory)
        AppBuildNumber: $(AppBuildNumber)
        AppVersionNumber: $(AppVersionNumber)
        BuildConfiguration: ${{ variables.BuildConfiguration }}
        ConfigFileFolderPath: '$(Build.Repository.LocalPath)/${{ variables.ConfigFileFolderPath}}/'
        FileEncryptorPath: '$(Build.Repository.LocalPath)/${{ variables.FileEncryptorPath}}'
        ConfigFileName: ${{ variables.ConfigFileName}}
        BuildType: ${{ variables.BuildType }}
        

  - stage: iOSAppBuild
    displayName: iOS App Build
    dependsOn: [UnitTestBuild]
    variables:
      AppBuildNumber: $[counter('${{ variables.AppVersionMajorMinor}}{{variables.BuildType}}', 0)]
    jobs:
    - template: ../jobs/ios-build-job-speedy.yaml
      parameters:
        BundleArtifactFolder: $(Build.Artifactstagingdirectory)
        SolutionFile: ${{ variables.Build_Projects }}
        BuildConfiguration: ${{ variables.BuildConfiguration }}
        AppVersionNumber: ${{ variables.AppVersionMajorMinor}}$(AppBuildNumber).0
        iOSCertSecureFile: ${{ variables.iOSCertSecureFile }}

  - stage: UWPAppBuild
    displayName: UWP App Build
    dependsOn: []
    variables:
      AppBuildNumber: $[counter('${{ variables.AppVersionMajorMinor}}{{variables.BuildType}}', 0)]
    jobs:
    - template: ../jobs/uwp-build-job-speedy.yaml
      parameters:
        BundleArtifactFolder: $(Build.Artifactstagingdirectory)
        SolutionFile: ${{ variables.Build_Projects }}
        BuildConfiguration: ${{ variables.BuildConfiguration }}
        BuildPlatform: ${{ variables.UWPBuildPlatform }}
        AppxPackageDir: $(Build.Artifactstagingdirectory)\${{ variables.AppxPackageDir }}
        AppxManifestPath: ${{ variables.AppxManifestPath }}

  - stage: AndroidAcceptanceTestsRunStage
    displayName: Acceptance Tests on Android App
    dependsOn: [AndroidAppBuild]
    variables:
      CurrentBuildId: '$(build.buildId)'
    jobs:    
    - template: ../jobs/android-acceptance-test-job.yaml
      parameters:
        AndroidBuildArtifact: ${{ variables.AndroidBuildArtifact }}
        APKFile: ${{ variables.APKFile }}
        AcceptanceTestProject: ${{ variables.AcceptanceTestProject }}

  - stage: IOSAcceptanceTestsRunStage
    displayName: Acceptance Tests on IOS App
    dependsOn: [iOSAppBuild]
    variables:
      CurrentBuildId: '$(build.buildId)'
    jobs:
    - template: ../jobs/ios-acceptance-test-job.yaml
      parameters:
        iOSBuildArtifact: ${{ variables.iOSBuildArtifact }}
        IPAFILE: ${{ variables.IPAFILE }}
        AcceptanceTestProject: ${{ variables.AcceptanceTestProject }}
